[changelog]
header = """
# Changelog do Vox AI

Todas as alterações notáveis neste projeto serão documentadas neste arquivo.

Arquivo gerado automaticamente via `git-cliff`.

"""
body = """
## {{ version }} - {{ timestamp | date(format="%d/%m/%Y") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
* {{ commit.message | upper_first }}
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false

tag_pattern = "^v[0-9].*"
ignore_tags = "dev-*"

commit_parsers = [
    { message = "^chore\\(release\\):", skip = true },
    { message = "^chore: sync CHANGELOG", skip = true },

    { message = "^feat", group = "✨ Funcionalidades" },
    { message = "^fix", group = "🐛 Correções" },
    { message = "^doc", group = "📚 Documentação" },
    { message = "^perf", group = "⚡ Performance" },

    { message = "^refactor", group = "♻️ Refatoração & Melhorias"},
    { message = "^style", group = "🎨 Estilo e Formatação"},
    { message = "^ci", group = "🤖 CI/CD & Automação"},
    { message = "^build", group = "📦 Build & Dependências"},
    { message = "^chore", group = "🔧 Tarefas Internas"},
    { message = "^test", group = "🧪 Testes Unitários e de Integração"},
]

filter_commits = false
