drop extension if exists "pg_net";

create extension if not exists "vector" with schema "public";

create sequence "public"."kb_id_seq";

create sequence "public"."report_categories_id_seq";


  create table "public"."chat_logs" (
    "chat_id" bigint generated by default as identity not null,
    "session_id" text,
    "prompt" text,
    "response" text,
    "git_version" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."chat_logs" enable row level security;


  create table "public"."chat_logs_kb" (
    "chat_log_kb_id" bigint generated by default as identity not null,
    "chat_id" bigint not null,
    "kb_id" text not null,
    "created_at" timestamp with time zone default now(),
    "similarity" double precision
      );


alter table "public"."chat_logs_kb" enable row level security;


  create table "public"."error_logs" (
    "id" bigint generated always as identity not null,
    "error_id" text,
    "error_message" text,
    "session_id" text,
    "git_version" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."error_logs" enable row level security;


  create table "public"."knowledge_base" (
    "kb_id" text not null default ('vox-kb-'::text || lpad((nextval('public.kb_id_seq'::regclass))::text, 4, '0'::text)),
    "topico" text,
    "eixo_tematico" text,
    "descricao" text not null,
    "referencias" text,
    "tags" text[],
    "autor" text,
    "created_at" timestamp with time zone default now(),
    "kb_count" numeric,
    "embedding" public.vector(768),
    "modificado_em" timestamp with time zone default now()
      );


alter table "public"."knowledge_base" enable row level security;


  create table "public"."knowledge_base_etl" (
    "kb_id" text not null default ('vox-kb-'::text || lpad((nextval('public.kb_id_seq'::regclass))::text, 4, '0'::text)),
    "topico" text,
    "eixo_tematico" text,
    "descricao" text not null,
    "referencias" text,
    "tags" text[],
    "autor" text,
    "created_at" timestamp with time zone default now(),
    "kb_count" numeric,
    "embedding" public.vector,
    "modificado_em" timestamp with time zone default now()
      );


alter table "public"."knowledge_base_etl" enable row level security;


  create table "public"."report_categories" (
    "id" integer not null default nextval('public.report_categories_id_seq'::regclass),
    "label" text,
    "description" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."report_categories" enable row level security;


  create table "public"."sessions" (
    "session_id" text not null,
    "created_at" timestamp with time zone default now(),
    "id" bigint generated by default as identity not null
      );


alter table "public"."sessions" enable row level security;


  create table "public"."user_reports" (
    "id" bigint generated always as identity not null,
    "session_id" text,
    "git_version" text,
    "chat_history" text,
    "created_at" timestamp with time zone default now(),
    "category_id" bigint,
    "comment" text
      );


alter table "public"."user_reports" enable row level security;

alter sequence "public"."report_categories_id_seq" owned by "public"."report_categories"."id";

CREATE UNIQUE INDEX chat_log_kb_chat_log_kb_id_key ON public.chat_logs_kb USING btree (chat_log_kb_id);

CREATE UNIQUE INDEX chat_log_kb_pkey ON public.chat_logs_kb USING btree (chat_log_kb_id);

CREATE UNIQUE INDEX chat_logs_pkey ON public.chat_logs USING btree (chat_id);

CREATE UNIQUE INDEX error_logs_pkey ON public.error_logs USING btree (id);

CREATE INDEX idx_chat_logs_kb_log ON public.chat_logs_kb USING btree (chat_log_kb_id);

CREATE INDEX idx_chat_logs_session_id ON public.chat_logs USING btree (session_id);

CREATE INDEX idx_error_logs_session_id ON public.error_logs USING btree (session_id);

CREATE INDEX idx_kb_eixo ON public.knowledge_base USING btree (eixo_tematico);

CREATE INDEX idx_kb_embedding ON public.knowledge_base USING hnsw (embedding public.vector_cosine_ops);

CREATE INDEX idx_kb_topico ON public.knowledge_base USING btree (topico);

CREATE INDEX idx_user_reports_session_id ON public.user_reports USING btree (session_id);

CREATE UNIQUE INDEX knowledge_base_etl_pkey ON public.knowledge_base_etl USING btree (kb_id);

CREATE UNIQUE INDEX knowledge_base_pkey ON public.knowledge_base USING btree (kb_id);

CREATE UNIQUE INDEX report_categories_pkey ON public.report_categories USING btree (id);

CREATE UNIQUE INDEX sessions_id_key ON public.sessions USING btree (id);

CREATE UNIQUE INDEX sessions_pkey ON public.sessions USING btree (session_id);

CREATE UNIQUE INDEX user_reports_pkey ON public.user_reports USING btree (id);

alter table "public"."chat_logs" add constraint "chat_logs_pkey" PRIMARY KEY using index "chat_logs_pkey";

alter table "public"."chat_logs_kb" add constraint "chat_log_kb_pkey" PRIMARY KEY using index "chat_log_kb_pkey";

alter table "public"."error_logs" add constraint "error_logs_pkey" PRIMARY KEY using index "error_logs_pkey";

alter table "public"."knowledge_base" add constraint "knowledge_base_pkey" PRIMARY KEY using index "knowledge_base_pkey";

alter table "public"."knowledge_base_etl" add constraint "knowledge_base_etl_pkey" PRIMARY KEY using index "knowledge_base_etl_pkey";

alter table "public"."report_categories" add constraint "report_categories_pkey" PRIMARY KEY using index "report_categories_pkey";

alter table "public"."sessions" add constraint "sessions_pkey" PRIMARY KEY using index "sessions_pkey";

alter table "public"."user_reports" add constraint "user_reports_pkey" PRIMARY KEY using index "user_reports_pkey";

alter table "public"."chat_logs" add constraint "chat_logs_session_id_fkey" FOREIGN KEY (session_id) REFERENCES public.sessions(session_id) ON DELETE RESTRICT not valid;

alter table "public"."chat_logs" validate constraint "chat_logs_session_id_fkey";

alter table "public"."chat_logs_kb" add constraint "chat_log_kb_chat_id_fkey" FOREIGN KEY (chat_id) REFERENCES public.chat_logs(chat_id) ON UPDATE CASCADE not valid;

alter table "public"."chat_logs_kb" validate constraint "chat_log_kb_chat_id_fkey";

alter table "public"."chat_logs_kb" add constraint "chat_log_kb_chat_log_kb_id_key" UNIQUE using index "chat_log_kb_chat_log_kb_id_key";

alter table "public"."chat_logs_kb" add constraint "chat_log_kb_kb_id_fkey" FOREIGN KEY (kb_id) REFERENCES public.knowledge_base(kb_id) ON UPDATE CASCADE not valid;

alter table "public"."chat_logs_kb" validate constraint "chat_log_kb_kb_id_fkey";

alter table "public"."error_logs" add constraint "error_logs_session_id_fkey" FOREIGN KEY (session_id) REFERENCES public.sessions(session_id) ON DELETE RESTRICT not valid;

alter table "public"."error_logs" validate constraint "error_logs_session_id_fkey";

alter table "public"."sessions" add constraint "sessions_id_key" UNIQUE using index "sessions_id_key";

alter table "public"."user_reports" add constraint "user_reports_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.report_categories(id) ON UPDATE CASCADE not valid;

alter table "public"."user_reports" validate constraint "user_reports_category_id_fkey";

alter table "public"."user_reports" add constraint "user_reports_session_id_fkey" FOREIGN KEY (session_id) REFERENCES public.sessions(session_id) ON DELETE RESTRICT not valid;

alter table "public"."user_reports" validate constraint "user_reports_session_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.increment_kb_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  UPDATE knowledge_base
  set kb_count = kb_count + 1
  where kb_id = new.kb_id;
  return new;
end
$function$
;

CREATE OR REPLACE FUNCTION public.match_knowledge_base(query_embedding public.vector, match_threshold double precision, match_count integer, filter_topic text DEFAULT NULL::text)
 RETURNS TABLE(id text, topico text, eixo_tematico text, descricao text, similarity double precision)
 LANGUAGE plpgsql
AS $function$
  BEGIN
    return query
    select
      knowledge_base.kb_id,
      knowledge_base.topico,
      knowledge_base.eixo_tematico,
      knowledge_base.descricao,
      1 - (knowledge_base.embedding <=> query_embedding) as similarity
    from knowledge_base
    where 1 - (knowledge_base.embedding <=> query_embedding) > match_threshold
    and (filter_topic is null or knowledge_base.topico = filter_topic)
    order by knowledge_base.embedding <=> query_embedding
    limit match_count;
  END;
  $function$
;

CREATE OR REPLACE FUNCTION public.update_modificado_em()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.modificado_em = now();
    RETURN NEW;
END;
$function$
;

grant delete on table "public"."chat_logs" to "anon";

grant insert on table "public"."chat_logs" to "anon";

grant references on table "public"."chat_logs" to "anon";

grant select on table "public"."chat_logs" to "anon";

grant trigger on table "public"."chat_logs" to "anon";

grant truncate on table "public"."chat_logs" to "anon";

grant update on table "public"."chat_logs" to "anon";

grant delete on table "public"."chat_logs" to "authenticated";

grant insert on table "public"."chat_logs" to "authenticated";

grant references on table "public"."chat_logs" to "authenticated";

grant select on table "public"."chat_logs" to "authenticated";

grant trigger on table "public"."chat_logs" to "authenticated";

grant truncate on table "public"."chat_logs" to "authenticated";

grant update on table "public"."chat_logs" to "authenticated";

grant delete on table "public"."chat_logs" to "service_role";

grant insert on table "public"."chat_logs" to "service_role";

grant references on table "public"."chat_logs" to "service_role";

grant select on table "public"."chat_logs" to "service_role";

grant trigger on table "public"."chat_logs" to "service_role";

grant truncate on table "public"."chat_logs" to "service_role";

grant update on table "public"."chat_logs" to "service_role";

grant delete on table "public"."chat_logs_kb" to "anon";

grant insert on table "public"."chat_logs_kb" to "anon";

grant references on table "public"."chat_logs_kb" to "anon";

grant select on table "public"."chat_logs_kb" to "anon";

grant trigger on table "public"."chat_logs_kb" to "anon";

grant truncate on table "public"."chat_logs_kb" to "anon";

grant update on table "public"."chat_logs_kb" to "anon";

grant delete on table "public"."chat_logs_kb" to "authenticated";

grant insert on table "public"."chat_logs_kb" to "authenticated";

grant references on table "public"."chat_logs_kb" to "authenticated";

grant select on table "public"."chat_logs_kb" to "authenticated";

grant trigger on table "public"."chat_logs_kb" to "authenticated";

grant truncate on table "public"."chat_logs_kb" to "authenticated";

grant update on table "public"."chat_logs_kb" to "authenticated";

grant delete on table "public"."chat_logs_kb" to "service_role";

grant insert on table "public"."chat_logs_kb" to "service_role";

grant references on table "public"."chat_logs_kb" to "service_role";

grant select on table "public"."chat_logs_kb" to "service_role";

grant trigger on table "public"."chat_logs_kb" to "service_role";

grant truncate on table "public"."chat_logs_kb" to "service_role";

grant update on table "public"."chat_logs_kb" to "service_role";

grant delete on table "public"."error_logs" to "anon";

grant insert on table "public"."error_logs" to "anon";

grant references on table "public"."error_logs" to "anon";

grant select on table "public"."error_logs" to "anon";

grant trigger on table "public"."error_logs" to "anon";

grant truncate on table "public"."error_logs" to "anon";

grant update on table "public"."error_logs" to "anon";

grant delete on table "public"."error_logs" to "authenticated";

grant insert on table "public"."error_logs" to "authenticated";

grant references on table "public"."error_logs" to "authenticated";

grant select on table "public"."error_logs" to "authenticated";

grant trigger on table "public"."error_logs" to "authenticated";

grant truncate on table "public"."error_logs" to "authenticated";

grant update on table "public"."error_logs" to "authenticated";

grant delete on table "public"."error_logs" to "service_role";

grant insert on table "public"."error_logs" to "service_role";

grant references on table "public"."error_logs" to "service_role";

grant select on table "public"."error_logs" to "service_role";

grant trigger on table "public"."error_logs" to "service_role";

grant truncate on table "public"."error_logs" to "service_role";

grant update on table "public"."error_logs" to "service_role";

grant delete on table "public"."knowledge_base" to "anon";

grant insert on table "public"."knowledge_base" to "anon";

grant references on table "public"."knowledge_base" to "anon";

grant select on table "public"."knowledge_base" to "anon";

grant trigger on table "public"."knowledge_base" to "anon";

grant truncate on table "public"."knowledge_base" to "anon";

grant update on table "public"."knowledge_base" to "anon";

grant delete on table "public"."knowledge_base" to "authenticated";

grant insert on table "public"."knowledge_base" to "authenticated";

grant references on table "public"."knowledge_base" to "authenticated";

grant select on table "public"."knowledge_base" to "authenticated";

grant trigger on table "public"."knowledge_base" to "authenticated";

grant truncate on table "public"."knowledge_base" to "authenticated";

grant update on table "public"."knowledge_base" to "authenticated";

grant delete on table "public"."knowledge_base" to "service_role";

grant insert on table "public"."knowledge_base" to "service_role";

grant references on table "public"."knowledge_base" to "service_role";

grant select on table "public"."knowledge_base" to "service_role";

grant trigger on table "public"."knowledge_base" to "service_role";

grant truncate on table "public"."knowledge_base" to "service_role";

grant update on table "public"."knowledge_base" to "service_role";

grant delete on table "public"."knowledge_base_etl" to "anon";

grant insert on table "public"."knowledge_base_etl" to "anon";

grant references on table "public"."knowledge_base_etl" to "anon";

grant select on table "public"."knowledge_base_etl" to "anon";

grant trigger on table "public"."knowledge_base_etl" to "anon";

grant truncate on table "public"."knowledge_base_etl" to "anon";

grant update on table "public"."knowledge_base_etl" to "anon";

grant delete on table "public"."knowledge_base_etl" to "authenticated";

grant insert on table "public"."knowledge_base_etl" to "authenticated";

grant references on table "public"."knowledge_base_etl" to "authenticated";

grant select on table "public"."knowledge_base_etl" to "authenticated";

grant trigger on table "public"."knowledge_base_etl" to "authenticated";

grant truncate on table "public"."knowledge_base_etl" to "authenticated";

grant update on table "public"."knowledge_base_etl" to "authenticated";

grant delete on table "public"."knowledge_base_etl" to "service_role";

grant insert on table "public"."knowledge_base_etl" to "service_role";

grant references on table "public"."knowledge_base_etl" to "service_role";

grant select on table "public"."knowledge_base_etl" to "service_role";

grant trigger on table "public"."knowledge_base_etl" to "service_role";

grant truncate on table "public"."knowledge_base_etl" to "service_role";

grant update on table "public"."knowledge_base_etl" to "service_role";

grant delete on table "public"."report_categories" to "anon";

grant insert on table "public"."report_categories" to "anon";

grant references on table "public"."report_categories" to "anon";

grant select on table "public"."report_categories" to "anon";

grant trigger on table "public"."report_categories" to "anon";

grant truncate on table "public"."report_categories" to "anon";

grant update on table "public"."report_categories" to "anon";

grant delete on table "public"."report_categories" to "authenticated";

grant insert on table "public"."report_categories" to "authenticated";

grant references on table "public"."report_categories" to "authenticated";

grant select on table "public"."report_categories" to "authenticated";

grant trigger on table "public"."report_categories" to "authenticated";

grant truncate on table "public"."report_categories" to "authenticated";

grant update on table "public"."report_categories" to "authenticated";

grant delete on table "public"."report_categories" to "service_role";

grant insert on table "public"."report_categories" to "service_role";

grant references on table "public"."report_categories" to "service_role";

grant select on table "public"."report_categories" to "service_role";

grant trigger on table "public"."report_categories" to "service_role";

grant truncate on table "public"."report_categories" to "service_role";

grant update on table "public"."report_categories" to "service_role";

grant delete on table "public"."sessions" to "anon";

grant insert on table "public"."sessions" to "anon";

grant references on table "public"."sessions" to "anon";

grant select on table "public"."sessions" to "anon";

grant trigger on table "public"."sessions" to "anon";

grant truncate on table "public"."sessions" to "anon";

grant update on table "public"."sessions" to "anon";

grant delete on table "public"."sessions" to "authenticated";

grant insert on table "public"."sessions" to "authenticated";

grant references on table "public"."sessions" to "authenticated";

grant select on table "public"."sessions" to "authenticated";

grant trigger on table "public"."sessions" to "authenticated";

grant truncate on table "public"."sessions" to "authenticated";

grant update on table "public"."sessions" to "authenticated";

grant delete on table "public"."sessions" to "service_role";

grant insert on table "public"."sessions" to "service_role";

grant references on table "public"."sessions" to "service_role";

grant select on table "public"."sessions" to "service_role";

grant trigger on table "public"."sessions" to "service_role";

grant truncate on table "public"."sessions" to "service_role";

grant update on table "public"."sessions" to "service_role";

grant delete on table "public"."user_reports" to "anon";

grant insert on table "public"."user_reports" to "anon";

grant references on table "public"."user_reports" to "anon";

grant select on table "public"."user_reports" to "anon";

grant trigger on table "public"."user_reports" to "anon";

grant truncate on table "public"."user_reports" to "anon";

grant update on table "public"."user_reports" to "anon";

grant delete on table "public"."user_reports" to "authenticated";

grant insert on table "public"."user_reports" to "authenticated";

grant references on table "public"."user_reports" to "authenticated";

grant select on table "public"."user_reports" to "authenticated";

grant trigger on table "public"."user_reports" to "authenticated";

grant truncate on table "public"."user_reports" to "authenticated";

grant update on table "public"."user_reports" to "authenticated";

grant delete on table "public"."user_reports" to "service_role";

grant insert on table "public"."user_reports" to "service_role";

grant references on table "public"."user_reports" to "service_role";

grant select on table "public"."user_reports" to "service_role";

grant trigger on table "public"."user_reports" to "service_role";

grant truncate on table "public"."user_reports" to "service_role";

grant update on table "public"."user_reports" to "service_role";


  create policy "Permitir leitura pública da KB"
  on "public"."knowledge_base"
  as permissive
  for select
  to anon
using (true);


CREATE TRIGGER tg_update_kb_usage AFTER INSERT ON public.chat_logs_kb FOR EACH ROW EXECUTE FUNCTION public.increment_kb_count();

CREATE TRIGGER update_kb_modificado_em BEFORE UPDATE ON public.knowledge_base FOR EACH ROW EXECUTE FUNCTION public.update_modificado_em();

CREATE TRIGGER update_kb_etl_modificado_em BEFORE UPDATE ON public.knowledge_base_etl FOR EACH ROW EXECUTE FUNCTION public.update_modificado_em();


